package com.chatbot.chat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChatResponse {

    /** The SQL query generated by the LLM */
    private String generatedSql;

    /** Visualization type: table | bar | line | pie | doughnut */
    private String type;

    /** Column names from the query result */
    private List<String> columns;

    /** All result rows as list of maps */
    private List<Map<String, Object>> data;

    /** Chart configuration decided by LLM */
    private ChartConfig chartConfig;

    /** Total number of rows returned */
    private int totalRows;

    /** Error message if something went wrong */
    private String error;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ChartConfig {
        private String title;
        private String labelColumn;
        private List<String> valueColumns;
    }
}
